### ISSUE TITLE
Architecture document not accessible

### ISSUE THREAD

**Issue by nremond** [flipkart-incubator/chronosq#2]
The Readme document feature a link to the architecture of the application: https://docs.google.com/presentation/d/1ykneLhJIf6r1cydbYVGV2dwtZjSNCW5lz7EbKHJDdBM/edit#slide=id.plink

Unfortunately, the document is not public and thus, can't be read.

**Comment by kingster** [comment]
Have updated the readme to make the image publicly visible. 

Sorry for the really late reply!
